name: Learning Github Action
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: moyed/github-actions-learning
          ref: main
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Debug File Structure
        run: |
          echo "Listing all files in the repository"
          ls -R
          echo "Current directory:"
          pwd
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Run Feed Generator
        run: python feed.py
      
      - name: Push Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "modified feed" || echo "No changes to commit"
          git push
